# Generated by Django 4.2.3 on 2023-09-08 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='books_img')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='library_app.bookcategory')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profiles/profile.png', null=True, upload_to='profiles')),
                ('school', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBooktoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(auto_now=True)),
                ('expiredate', models.DateField(default=library_app.models.get_expiry)),
                ('fines', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100, null=True)),
                ('book', models.OneToOneField(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='library_app.books')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='library_app.studentextra')),
            ],
            options={
                'ordering': ['-issuedate'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(db_column='school', on_delete=django.db.models.deletion.CASCADE, to='library_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timesend', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowbooksummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Available', 'Availabe'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Not Available', 'Not Available')], max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='library_app.books')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='library_app.studentextra')),
            ],
            options={
                'verbose_name_plural': 'Borrowbooksummary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BorrowBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusoption', models.CharField(choices=[('Borrow', 'Borrow')], default='Borrow', max_length=100)),
                ('borrowdate', models.DateField(auto_now=True)),
                ('book', models.OneToOneField(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='library_app.books')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='library_app.studentextra')),
            ],
        ),
    ]
